### ISSUE TITLE
Updating FAQ page

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#1]
I would like to be able to easily manage the FAQ page from the back end admin dashboard

**Comment by cgladue** [comment]
got it...

**Comment by cgladue** [comment]
and the How it works page as well ?

**Comment by robgpeak** [comment]
Yes.

Thanks,

Rob

**Sent from my phone

**Comment by robgpeak** [comment]
Any progress on this over last weekend @cgladue ?

**Comment by cgladue** [comment]
yep, should be done very soon



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
👍

**Comment by cgladue** [comment]
https://shop.complinks.co/admindashboard/partners/faq

**Comment by robgpeak** [comment]
Awesome!  Thanks @cgladue

**Comment by robgpeak** [comment]
@cgladue One thing on the date and time in the "Last Updated" column, when you update any FAQ, it not only records the date and time for that update, but for all the subsequent items listed below it at the same time, even though those other items we note updated.  It should be just updating the specific item that was updated.

**Comment by cgladue** [comment]
did you "insert" an item ?  like with a display order that was already
being used ?  if there is 3 items, display 1, 2, 3 and you create a new
item and give it order of 2, what its doing in the background is going and
updating 2 and 3 to 3 and 4 and inserting the new item as 2, so technically
2 3 and 4 would have the same updatedtime since the database considers it
updated.

i can get around it with some more effort tho if thats causing issues.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
In this particular case, I updated item number 16 "What can I do with my points?" specifically on xclub's FAQ page, and it changed the Last Updated for all the subsequent item numbers with the same date and time, AS WELL AS the ones on shop's FAQ admin page.  Let's put this in as a low priority...

**Comment by cgladue** [comment]
ok, i have an idea what it is, but ill get to it when i can



Chad Gladue
*DevNull Technology, LLC*
