### ISSUE TITLE
Integrate Parx Casino Account Linking

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#14]

**Comment by cgladue** [comment]
Parx Test Account Numbers:

Account - Zip
1423818 - 19020
1423986 - 19020 
1424165 - 19020
1425289 - 19020
1425648 - 19020
1423980 - 19201

**Comment by robgpeak** [comment]
@cgladue I am not really sure what I am supposed to be doing with this issue with it being in review?

I am assuming they (Parx) uses "Account Number" and "Zip" to authenticate a user, so on the ./account/myprofile page, the second field should say "Zip Code" instead of "PIN"

Also, please change the term on that same page to read, "... then click "Link Account" (singular) instead of "Accounts", so it matches what the button actually reads.

<img width="567" alt="screen shot 2018-02-21 at 10 16 30 am" src="https://user-images.githubusercontent.com/28393235/36488168-cb61d78c-16f0-11e8-845f-d195b27248a1.png">

**Comment by cgladue** [comment]
you can test linking an account and transferring points, the whole process.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
OK, I just tried one.  I linked my Rewards Everywhere account 100086 with Xclub account 1425289 (successfully), and then when I attempted to make a transfer of 1,000 points, it told me it worked, but it did not deduct the points from my RE balance...  I started with 10,000, and after the successful transfer, I was still left with 10,000, and in the "Points Used" column below in the Points Exchanged area did NOT should the 1,000 points that I transferred. 

<img width="913" alt="screen shot 2018-02-21 at 10 24 59 am" src="https://user-images.githubusercontent.com/28393235/36488597-d9bc95f0-16f1-11e8-9bdc-fe086a089b7c.png">

**Comment by cgladue** [comment]
ok the reward is probbally misconfigured for this partner let me look



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
it was, there is a hidden flag for "freeform" which signifies that the reward is user definable value, it was set to false, and the configured value was 0 so it redeemed as 0 points...  i have set that switch to true and now it should work... also changed the Link Accounts to Link Account
