### ISSUE TITLE
Convert How it works page to dynamic page

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#2]
Need to control content on how it works page by partner.

**Comment by robgpeak** [comment]
Once this and the FAQ page are done like the promotions page, I can make all the text edits that Marc and Nicolle suggested.

**Comment by cgladue** [comment]
https://shop.complinks.co/admindashboard/partners/faq

**Comment by robgpeak** [comment]
@cgladue I just updated some of the copy in the paragraph of the first section, but when I saved it and looked at it love on the site, it took the "clickable button" effect away from the 'Start Saving Now' button at the bottom of the paragraph.  I think that bit of text needs to be in its own separate column so it retains its "clickability.  

Speaking of which, it currently links to the sign in screen overlay, but if I am already logged in, that seems pretty dumb.  If I am already authenticated, maybe it should just take me to the home page so i can start shopping.

**Comment by cgladue** [comment]
Its always taken you to the login screen...

and as for the button dissapearing its because i cannot display the button chris created in the HTML editor

so you have to put in the shortcode every time, i can get around this by not using an HTML editor and just showing the raw HTML but its not as friendly...

**Comment by robgpeak** [comment]
I get that it always takes you to the log in screen, but from a better UX
perspective, this does not make sense if you are already logged in.

As for the clickable button, just let me know what the short code is, and I
will put it in every time.

Thanks,

Rob

**Sent from my phone

On Feb 18, 2018 1:06 PM, "cgladue" <notifications@github.com> wrote:

Its always taken you to the login screen...

and as for the button dissapearing its because i cannot display the button
chris created in the HTML editor

so you have to put in the shortcode every time, i can get around this by
not using an HTML editor and just showing the raw HTML but its not as
friendly...

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/robgpeak/CompLinks-xclub/issues/2#issuecomment-366534708>,
or mute the thread

**Comment by robgpeak** [comment]
@cgladue What if you use the HTML editor like this one https://www.tinymce.com/ that is WYSIWYG, but then I can see the code, so I can put in the short code for the button.

**Comment by cgladue** [comment]
that is the exact one i am using already ...  but you cannot enter HTML
manually without buying a license for it...  the "community version" dosnt
allow direct raw html editing.



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
How much is the license?  Would it be the self hosted option for the Developer $156 for the year?  If so, that's fine, we can buy it.

**Comment by cgladue** [comment]
i found CkEditor


https://docs.ckeditor.com/ckeditor4/latest/guide/dev_framed.html

i think the free version may work let me try that first, but i think
TinyMCE is a monthly subscription so its ongoing like $10 a month ...



Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
@cgladue any feedback/progress on this?

**Comment by robgpeak** [comment]
I moved this back to Backlog from Review becasue it is related to the comment you made in the threa
