### ISSUE TITLE
Game Interstitial visibility

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#224]
@cgladue we need to add a Game Interstitial: "Active/Inactive" option in the edit screen of the "Property List" for each domain so we can easily control which subdomains see the game interstitials and which don't.  Meaning, I am sure there will be some subdomains that do not want the games to appear on.

**Comment by robgpeak** [comment]
Not sure if this should be a different issue, but additionally, we want to allow each person to opt in/out of seeing the Feeling Lucky screen.

**Comment by cgladue** [comment]
@robgpeak so they would go into their settings and set a flag whether or not they want to see the bonus point game offers, correct ?

**Comment by cgladue** [comment]
@robgpeak there is now a new dropdown in the Property edit modal to enable bonus games, also there is a new field added to the user table to store if the user wants to see game offers, right now everyone is defaulted to false since i tried adding the checkbox to the profile and it didnt take, so that needs chris as well.  but the data is there in the database i can manually set it to whatever you want for your testing   both the user has to be opted in and the property has to be anabled in order for the game to show.

**Comment by robgpeak** [comment]
OK.  They will all default to true.  So if you can set it that way in the db, that would be better, and then I will reach out to Chris next week and see about getting him to beautify everything and make sure functionality all working well for the UX.

**Comment by cgladue** [comment]
ok, all the users default to true, but the properties default to false.
except shop. that one i set to true


Chad Gladue
*DevNull Technology, LLC*

**Comment by robgpeak** [comment]
👍
