### ISSUE TITLE
Update CJ, Impact and Linkshare with new domain name 

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#272]
i bet there is some setting somewhere in the backend of these sites that asks for the domain name of the site so they can expect the traffic from it.

**Comment by robgpeak** [comment]
Yes there is, but we can only list it when the site is live, otherwise it will be rejected.

Which begs the question, can we run both domains shop.rewardseverywhere.co and shop.complinks.co and their subs in parallel?  So they would both be pointing to the same site and would theoretically interchangeable?

**Comment by cgladue** [comment]
Yea we can.  Go to shop.rewardseverywhere.co. NOw for example

**Comment by robgpeak** [comment]
Cool.  And I was able to log in with my existing login credentials.  NICE!

**Comment by robgpeak** [comment]
https://shop.rewardseverywhere.co has been added to all three networks.

**Comment by robgpeak** [comment]
@morganpeak please add the domain as a source of traffic to Awin and Share a Sale
