### ISSUE TITLE
Some odd transactions showing up in my account

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#282]
Hey @cgladue please have a quick look https://www.loom.com/share/570583fd6ec143baac09467d117e12b0

**Comment by cgladue** [comment]
ok i found out that the travel trip was actually a walmart trip and i have no idea why it assigned it to you ... only thing i can think of is we were in the middle of a database migration and server move around that time and maybe something got messed up, since this woman 
![image](https://user-images.githubusercontent.com/7914133/66095016-0aab4e80-e564-11e9-9e41-4686e27d7a61.png)
had trip ID 7293 on the old database and you had trip 7294 on the new DB, i bet it got confused on who started trip and thought you did, i moved it over to her, it shouldbe gone from your view 

also the $35 is in fact the comission, travelpayouts does not include the total purchase price int he API so i have no idea how much the travel was for 

i think its a isolated incident

**Comment by cgladue** [comment]
i manually updated the advertiser to be walmart and assigned that trip to Candida as it should of been

**Comment by robgpeak** [comment]
Ok
