### ISSUE TITLE
API with GrooveHQ to show an end user's subscription level

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#36]
@cgladue I added you to GrooveHQ, and I wanted you to look into https://complinks.groovehq.com/groove_client/apps/mail-chimp so you can see how it would integrate with Mailchimp.

**Comment by cgladue** [comment]
Ok just checked out the groove Integration, pretty simple....  only one thing, all they send to us is the users email address and expect us to use that field to return profile data... since email is not unique in our system, the best i would be able to do would be return ALL partners that the user is a member of and the associated data...  does that work ?

**Comment by robgpeak** [comment]
Yeah I think that will work.

**Comment by cgladue** [comment]
![image](https://user-images.githubusercontent.com/7914133/37866500-c8d5616c-2f61-11e8-8c10-ddb67bdb4fba.png)

**Comment by cgladue** [comment]
See above for what it will look like when an email exists in the database, groove will now send a query to complinks to lookup the user and i respond with account number, name and partners, the account number links to the user view page in the backend.

@robgpeak

**Comment by robgpeak** [comment]
Awesome
