### ISSUE TITLE
Subdomain alternative

### ISSUE THREAD

**Issue by robgpeak** [robgpeak/CompLinks-xclub#388]
@cgladue On a similar issue to #379 I wanted to add another subdomain in order to present the platform to a company Team Meals.

I created a subdomain on Cloudflare, (myteammeals) but when I tried to add the new property in the back end, I got the same error message I got last time when I tried to add a new property.  I think you had to do something on the server to allow connections to that new subdomain.

Just thinking maybe it would be easier if there was an easier alternative method of setting up temporary sites more quickly if we had a URL naming convention like this for example https://rewardseverywhere.co/xclub that brought up everything as it currently does for xclub.rewardseverywhere.co

Just trying to think how we can make it easier to develop sites...

**Comment by robgpeak** [comment]
Any thoughts here @cgladue ?

**Comment by cgladue** [comment]
yea i am looking through where the issue is that causes you to not just be able to add it, its because of all the default FAQ, etc records that need to be created so it should just create them for you in theory then you can do it yourself in cloudflare (except the IIS binding will still have to be added manually tho)

**Comment by robgpeak** [comment]
Ok

Thanks,

Rob

*Sent from my phone

**Comment by cgladue** [comment]
did you remove the DNS from cloudflare ?  if you add it back i believe this is working now

**Comment by robgpeak** [comment]
Yes,it worked.  Thanks.
