### ISSUE TITLE
Need to call Javascript function when "Shop Now" buttons (<md-button>) are clicked

### ISSUE THREAD

**Issue by cgladue** [robgpeak/CompLinks-xclub#92]
Currently the site is doing a HTTP 302 redirect when sending the user to the affiliate URL, which clears the referrer out since its a Server redirect, we need to redo the way that our links work, and instead of going to a page on the server then the server redirecting, we need the browser to go directly to the referral URL itself... 

my thoughts:

Modify md-button elements that reference @advertiser.startTripLink so that the HREF = @advertiser.startTripLink like it does already, and add an onclick function or some other way intercept the user click so we can call the following function:

You can go to this URL to see the JSON that gets returned:
https://shop.complinks.co/trip/getUrl?aid=6789&lid=0&url=http%3a%2f%2fclick.linksynergy.com%2ffs-bin%2fclick%3fid%3djLQ8qrFPMSA%26offerid%3d486109.100267309%26type%3d3

i know this dosnt work in angular, but youll get  what im thinking:

`<md-button class="md-secondary hide-sm md-raised md-accent" ng-href="@advertiser.startTripLink" ng-click="javascript:startTrip(@advertiser.advertiserId, 0, @advertiser.startTripLink);" target="_blank">Shop Now <md-icon>play_arrow</md-icon></md-button>`

the startTrip function is as follows:
```

function startTrip(aid, lid, url) {
    $.get("/trip/start?aid=" + aid + "&lid=" + lid + "&url=" + url, function (data) {
        window.location = data.redirectUrl;
    });

    return false;
}
```

it would prevent the browser from actually going to the HREF and instead redirect to the value thats returned from the getUrl ajax call.

**Comment by cgladue** [comment]
@robgpeak i think this would fix the referrer issue that CJ is seeing ...  just need @ChrisASearles to do an example of this (perhaps on the Home/Index.cshtml View?)  then i should be able to do the rest as long as its copy and paste

**Comment by ChrisASearles** [comment]
Hey @cgladue I'm assuming based on the code you outlined here that you want 0 passed in for the link id when there is no link id, correct?

**Comment by ChrisASearles** [comment]
and the mainLinkUrl passed as the starttriplink?

**Comment by cgladue** [comment]
That is correct.   There should always be a link ID unless they use the shop now button from the advertiser list.  In which case send 0.

**Comment by ChrisASearles** [comment]
As long as those assumptions are correct this should be working properly. @cgladue I changed the GetUrl method to a post and I'm passing the data in the request body. Everything is up and running and I believe I updated all occurrences on the front end (everywhere there was a startTripLink referenced has been updated, assuming that's everything?).

I also did a couple quick tests to make sure the referrer was being properly retained. If I remember correctly older versions of IE would clear the referrer on a window.location but I tested back to IE 10 on Win 8 and it was working as expected.

**Comment by cgladue** [comment]
You can keep using starttriplink. I’m going to adjust it on the backend.   To not include /trip/start

**Comment by cgladue** [comment]
Just to confirm.  I’d like the starttriplink put back.  I’ll adjust on the backend.

**Comment by cgladue** [comment]
@ChrisASearles i updated my working copy but i dont see the pages loading the result from the GetUrl call, its navigating to the href ... can you stop it from going to the href location and use the redirect value returned by the GetUrl call

**Comment by cgladue** [comment]
and there dosnt appear to be an "onclick" event ?  i dont see any HTTP Post before the page is loaded ... can you tell me what i am missing ?

**Comment by robgpeak** [comment]
@ChrisASearles where are we on this one?

**Comment by ChrisASearles** [comment]
@cgladue I just committed a new version of this. I think it's functioning the way you're looking for but I'm not 100% sure. In your original post you pasted that link to look at the structure of the JSON returned, however the sample method you posted called a different function. I assumed that was a typo and you wrote the new one to avoid double-posting 2 trips to the database (which is what I assumed the start trip link was doing, creating the trip in the DB) so I was using the method you posted that returned the structured data you mentioned and redirecting to the URL that was being passed back.

I'm not sure now if you want me calling /trip/start or trip/geturl? For now, it's written with /trip/geturl but redirecting to the startTripLink coming down to the view. Just doesn't seem right b/c that would mean I'm not doing anything with the data you're passing back from that call.

I'm going to be out of contact beginning about 4:30 this afternoon for the entire weekend moving my entire house so if you need to make changes to any of this and I'm not available, here's how the JS works:

/Scripts/dev/services.js is where the API call is spec'd:

```javascript
$http.post('/trip/geturl', tripModel).then(function (resp) { 
    deferred.resolve(resp.data);
 }, function (error) {
       deferred.reject(error);
});
```

Just change that relative URL to 'start' or whatever you need. ***Note this is an HTTP Post so you'd have to change the API method to a POST instead of a GET if you change where this posts it's data to.

The redirect is handled starting on line 44 of /Scripts/dev/controllers.js:

```javascript
$scope.startTrip = function (advertiserId, linkId, url, tripUrl) {
            $scope.error = null;
            tripSvc.startTrip(advertiserId, linkId, url).then(function (resp) {
                window.location = tripUrl;
            }, function (error) {
                console.error(error);
                $scope.error = "We're sorry but an error occurred while starting your trip, please try again. If the problem persists, please contact support.";
                window.scrollTo(0, 0);
            });
        };
```

If this needs to change to redirect to a URL coming from the API call, the 'resp' object on line 3 of that code block has the JSONified data that's coming back and can be accessed accordingly (e.g. resp.redirectUrl).

Also see that I missed those 4 feature advertisers on the homepage the first time around and fixed those links to call this function as well, but right now the ones that are coming down have a null or empty mainLinkURL.

I also updated the GetUrl method to wrap the whole thing in a try/catch and handle the exception a little more gracefully. At the moment, it means there's some detail on DB fields getting logged to the console in the event of an error at the DB. I'm not sure what you're doing in terms of logging on the server-side so I didn't log anything there but figured this at least might help you while you're testing and you can ditch the detailed error message if you want in favor of something more vague (or more targeted to whichever method is failing out).

Let me know if you need anything else from me on this, happy to help where I can.

**Comment by ChrisASearles** [comment]
Just realized I missed the main link on the store index page. That's been committed but has the same issue as the 4 featured links on the home page (null or empty mainLinkUrl). That update has been committed.

**Comment by robgpeak** [comment]
@cgladue is this still an issue or has it been resolved so our links are now in compliance?

**Comment by cgladue** [comment]
I didn’t want to make the update on the live site now that parks is basically life so check out Test.com links.co it’s hard coded to shop.com thanks.co domain so you can test out the links there and it will register under shop

**Comment by robgpeak** [comment]
OK, I just started two trips to CJ advertisers through test.complinks.co and it tracked the trips on our side, now I am going to ask CJ is they see the Referring URL properly on their side and I will let you know.  If it is OK on their side, would it still work if we pop it open in a new tab?  Right now it is opening the link to the advertiser in the same tab.

**Comment by cgladue** [comment]
i think i can change that to open in a new window ... or chris can i would
think ...



Chad Gladue
*DevNull Technology, LLC*

**Comment by cgladue** [comment]
wow my stupid voice to text on my phone, thats really bad :(

**Comment by robgpeak** [comment]
It does...  but I deciphered it.  I use google and it works pretty well

**Comment by cgladue** [comment]
So what its doing now is when you click the button, it does a background POST to our /trip/getUrl address, which starts the trip, and adds the trip ID to the URL and sends the URL back to the page, once the page gets that url back it navigates to that URL as if the user clicked on a link directly.  Which leaves the referrer intact.  instead of doing a server redirect which resets the referrer.

**Comment by robgpeak** [comment]
OK, that should work for their (cj's) compliance needs. Let's try it with it opening in a new tab and make sure it all works properly as far as retaining the referring URL, which I am sure it will.  Actually, now that I am thinking about it, instead of a full page interstitial, how about we try a modal with the spinning roulette wheel to earn extra points promotions and such.  These would keep the referring URL intact and still allow us to manage some engagement tools.  I am going to start another issue on this subject.

**Comment by cgladue** [comment]
This is now an intersticial Page
